// client/src/components/BucketCard.jsx
// src/components/BucketCard.js
import React from "react";

function BucketCard({ bucket }) {
  return (
    <div className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow">
      <h3 className="text-xl font-semibold mb-4">{bucket.Name}</h3>
      <p className="text-gray-600">Created: {bucket.CreationDate}</p>
      <p className="text-gray-600">Region: {bucket.Region}</p>
      {/* You can add more bucket details here */}
    </div>
  );
}

export default BucketCard;

// client/src/components/s3/BucketCard.vue
<script>
export default {
  props: {
    bucket: {
      type: Object,
      required: true
    }
  }
};
</script>

<template>
  <div class="border rounded-lg shadow p-5 bg-white max-w-sm">
    <h3 class="font-bold text-lg">{{ bucket.Name }}</h3>
    <p class="text-gray-800">Created on: {{ new Date(bucket.CreationDate).toLocaleString() }}</p>
  </div>
</template>

<style scoped>
/* Add any specific styling for the bucket card here */
</style>
